-- premake5.lua
-- generated by muhhae

workspace "CPPTemplate"
    configurations { "Debug", "Release" }

BUILDDIR = "bin" --Build Directory
OBJDIR = "obj" --Obj Directory
RESFILE = "resource" --Resource Directory

project "App"
    kind "ConsoleApp" --App Type
    language "C++" --Languange

    cppdialect "C++latest"
    links {} --link library
    includedirs {"include"}

    targetdir "%{BUILDDIR}/%{cfg.buildcfg}" 
    objdir "%{OBJDIR}/%{cfg.buildcfg}"

    SRCDIR = "Example" --Source Code Directory

    files {
        "%{SRCDIR}/**.h",
        "%{SRCDIR}/**.hpp", 
        "%{SRCDIR}/**.cpp",

        "%include/**.cpp",
        "%include/**.hpp",
        "%include/**.h"
    }

    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"

    filter "configurations:Release"
        defines { "RELEASE" }
        optimize "On"
        prebuildcommands { 
            "rm -rf %{BUILDDIR}/%{cfg.buildcfg}/resource",
            "{COPYDIR} %{RESFILE} %{BUILDDIR}/%{cfg.buildcfg}/resource" 
        }